apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  kustomize.buildOptions: "--enable-helm"
  statusbadge.enabled: "true"
  url: "https://argocd-raspberrypi.tail858f03.ts.net"
  resource.exclusions: |
    - apiGroups:
        - batch
      kinds:
        - Job
      clusters:
        - "*"
      names:
        - ingress-nginx-admission-patch
