apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  kustomize.buildOptions: "--enable-helm"
  statusbadge.enabled: "true"
  exec.enabled: "true"
  url: "https://argocd-raspberrypi.tail858f03.ts.net"
  dex.config: |
    connectors:
    - config:
        issuer: https://accounts.google.com
        clientID: $google-oidc:clientID
        clientSecret: $google-oidc:clientSecret
      type: oidc
      id: google
      name: Google
  resource.exclusions: |
    - apiGroups:
        - batch
      kinds:
        - Job
      clusters:
        - "*"
      names:
        - ingress-nginx-admission-patch
